Bridge C++ library core to PySCF
Yang-Laboratory/losc pull request #2
Opened 2021-07-26 01:18 UTC by pi246

Please let me know if there is any modification I should make! Thanks!

2021-07-26 06:24 UTC, zc62 requested changes

2021-07-26 06:24 UTC, zc62 commented on src/pyscf_losc/utils.py
> +
Extra empty lines

2021-07-26 06:24 UTC, zc62 commented on src/pyscf_losc/losc_options.py
> +        return '\n'.join(rst)
Configure your editor to always insert a newline, even if it is the end of file. This happens to all new files you created in this commit.
If using vscode, configure in this way:
```json
"files.insertFinalNewline": true,
```
Some others I use along with this setting:
```json
"files.trimTrailingWhitespace": true,
"files.trimFinalNewlines": true,
```

Or did you use any code formatter? If so, find corresponding configurations for that.

2021-07-26 06:24 UTC, zc62 commented on src/pyscf_losc/utils.py
> +
Extra empty lines. I think code formatters should catch these?

2021-07-26 06:31 UTC, zc62 commented
The code looks great, though I cannot really tell if it works as intended or not. I think it would be best if you can add unit tests. @Miocbb How did you do unit tests for the psi4 plugin?

In addition, I think proper documentation about how to use this plugin is required, otherwise people who are not familiar with this cannot easily use it. Refer to how @Miocbb wrote documentations for the psi4 plugin. See a bunch of rst files under https://github.com/Yang-Laboratory/losc/tree/2405d7b1e7d1d8f593403573f6af7a0b6b988c5e/docs_source/sphinx

2021-07-26 06:35 UTC, zc62 commented
And you can try to write more standardized git commit messages as well. [Here is what I saw and took as a good standard for commit messages.](https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md#write-good-commit-messages) You can also refer to the commit history of this repository and see how Miocbb wrote them.

2021-07-26 20:23 UTC, Miocbb commented
> The code looks great, though I cannot really tell if it works as intended or not. I think it would be best if you can add unit tests. @Miocbb How did you do unit tests for the psi4 plugin?
> 
> In addition, I think proper documentation about how to use this plugin is required, otherwise people who are not familiar with this cannot easily use it. Refer to how @Miocbb wrote documentations for the psi4 plugin. See a bunch of rst files under https://github.com/Yang-Laboratory/losc/tree/2405d7b1e7d1d8f593403573f6af7a0b6b988c5e/docs_source/sphinx

I made some simple tests for psi4_losc under losc/test/psi4_losc. @pi246

2021-11-13 03:19 UTC, merged

2021-11-13 03:25 UTC, zc62 commented
Not sure why this PR got merged without further review, as apparently 65099b36f97a9dfb7f7aa9b33ecf2407850ca9a5 got back those format issues that e42faebb5608290262f9e375ed1e7cb842cadfaf tried to resolve, for example. @pi246